version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./symfony:/var/www/html
    environment:
      # This DATABASE_URL should match your Symfony .env settings.
      DATABASE_URL: 'postgresql://symfony:secret@db:5432/symfony?serverVersion=13&charset=utf8'
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgdata:
